# These are supported funding model platforms
XLM: "GBUTD5DNV43JBJP7AA657H2CYPUCAAFBXCKX7QE4XXGYIYFZZX2EKKVF":, "Memo:" "1095780281" 
Etherium: "0xc78373B0A479b96c4092622cAfA2B65373E6c5DE" 
Solana: "9nps8QQcSp5rpZx2SdwbjNbSAVpDHH1RfFqkuKLRMQFj"
Bitcoin: "bc1q58mdap8gzdj5rkfgrk9n5ruz7hkzl5wch09e06"
